[package]
name = "deadpool-diesel-async"
version = "0.1.1"
authors = ["Trey Lowerison <trey@sidechainme.com>"]
edition = "2021"

[dependencies]
deadpool = { version = "0.9.3", features = ["managed", "rt_tokio_1"] }
diesel = { git = "https://github.com/diesel-rs/diesel", rev = "d8bb571", default-features = false }
diesel-async = { git = "https://github.com/weiznich/diesel_async", rev = "7052fe7a" }
thiserror = "1.0.30"
tokio = "1.17.0"

[features]
mysql = ["diesel/mysql", "diesel-async/mysql"]
postgres = ["diesel/postgres", "diesel-async/postgres"]
serde = ["deadpool/serde"]
