[package]
name = "deadpool-diesel-async-example"
version = "0.1.2"
edition = "2021"

[dependencies]
deadpool = { version = "0.9.3", features = ["managed", "rt_tokio_1"] }
deadpool-diesel-async = { path = ".." }
diesel = { git = "https://github.com/diesel-rs/diesel", rev = "d8bb571", features = ["extras", "numeric", "postgres"] }
diesel-async = { git = "https://github.com/weiznich/diesel_async", rev = "7052fe7a" }
tokio = { version = "1.17.0", features = ["full"] }

[features]
default = []
db_conn_wrapper = []
